In [27]:
import numpy as np
import src

import testFunctions as tf
from animation import animation, animation3D

def de():
    #instantiate solutions 
    X = np.array([src.solution(my_func, dimension, bounds) for i in range(n)])
    #initialize solutions 
    [Xi.initRandom() for Xi in X]
    
    #just so we can have some animations
    src.solution.updateHistory(X) # it is not necessary for the grammar
    
    for it in range(iteration):
        #1. Select individuals for modification in this round
        # none - select all. Alternative (bee algorythm) is to select only solutions drawn with fitness-dependant probability
        #2. de_operator = create an alternative set of solutions X1 using mutation+crossover
        X1  = src.op.op_de(X, src.op.select_random, src.op.mut_de, src.op.crx_exponential, **params)
        #3. Select individual for the next generation
        X = src.op.replace_if_best(X, X1)
        
        src.solution.updateHistory(X) 

    return X
    
##param
n = 30
iteration = 2

my_func   = tf.ackley_function
dimension = 5
bounds    = -10, 10

params = {'beta':.5, 'pr':.7, 'tournamment':5, 'w':.5, 'c1':.5, 'c2':1}

de()
src.solution.best.getFitness()
#animation(src.solution.history, my_func, *bounds)

4.341911398317924

In [2]:
iteration = 5
de()
src.solution.best.getFitness()

4.369884043319333

In [3]:
iteration = 10
de()
src.solution.best.getFitness()

6.466684771911655

In [4]:
iteration = 20
de()
src.solution.best.getFitness()

7.848034929833105

In [6]:
iteration = 100
de()
src.solution.best.getFitness()

8.901120164446802

In [3]:
x.best()

NameError: name 'x' is not defined

In [16]:
X = np.array([src.solution(my_func, dimension, bounds) for i in range(n)])
    #initialize solutions 
[Xi.initRandom() for Xi in X]
np.random.choice(X.shape[0], 1)

array([10])

In [28]:
U = np.array([src.solution(X[0].function, X[0].x.shape[0], X[0].limits) for i in range(X.shape[0])])
u = np.array([X[i].fitness for i in range(X.shape[0])])

In [92]:

    #instantiate solutions 
X = np.array([src.solution(my_func, dimension, bounds) for i in range(n)])
    #initialize solutions 
[Xi.initRandom() for Xi in X]
    
    
for it in range(iteration):
        #1. Select individuals for modification in this round
        # none - select all. Alternative (bee algorythm) is to select only solutions drawn with fitness-dependant probability
        #2. de_operator = create an alternative set of solutions X1 using mutation+crossover
    X  = src.op.op_de(X, src.op.select_random, src.op.mut_de, src.op.crx_exponential, **params)
        #3. Select individual for the next generation
    X = src.op.replace_if_best(X, X1)
    u = np.array([(X[i].fitness, i) for i in range(X.shape[0])])
#     v = u.sort(X, key=fitness) 
    
# X[1].fitness
# X.shape[0]
# u = sorted(u, key=lambda x:x[0])
# for i in range(len(u)//2):
#     if np.random() < pa:
#         ind = int(u[i][1])
#         X[ind] = initRandom(X[ind])



In [69]:
X[4].x
X[4].

array([ 8.51230616, -4.00468998, 15.24115881,  3.80482329,  6.62362067])

In [82]:
X[5].initRandom()

In [84]:
print(X[4])

In [85]:
pa = 0.25

[Xi.getFitness() for Xi in X]
u = np.array([(X[i].fitness, i) for i in range(X.shape[0])])
u = sorted(u, key=lambda x:x[0])
for i in range(20):
    if np.random.random() < pa:
        ind = int(u[i][1])
        X[ind].initRandom()
        print(X[ind])


In [102]:
u = np.array([mut_cs(X[i]) for i in range(X.shape[0])])
u

TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

In [103]:
from math import gamma, pi, sin
def mut_cs(x1, x2=None, x3=None, **param): 
    beta = 3 / 2
    sigma = (gamma(1 + beta) * sin(pi * beta / 2) / (gamma((1 + beta) / 2) * beta * 2 ** ((beta - 1) / 2))) ** (1 / beta)
    w = np.array(np.random.standard_normal(x1.x.shape)) * sigma
    v = np.array(np.random.standard_normal(x1.x.shape))
    step = w / abs(v) ** (1 / beta)

    x1.getFitness()
    stepsize = 0.2 * step * (x1.x - x1.pbest)
    u = x1.x + stepsize

    return u

In [111]:
def select_random(X, array, k=1, replace=True):
    return np.random.choice(array, k, replace=replace)
idx_tmp = np.arange(X.shape[0])
idx = np.array([np.append([i], select_random(X, np.delete(idx_tmp, i), 3, replace=False)) for i in range(X.shape[0])])


In [112]:
idx

array([[ 0,  9, 13,  8],
       [ 1,  6, 27, 26],
       [ 2, 23, 16, 26],
       [ 3,  8,  7, 18],
       [ 4, 16, 15, 22],
       [ 5, 22,  3, 29],
       [ 6, 28,  7, 21],
       [ 7,  0,  5, 19],
       [ 8, 10, 14, 19],
       [ 9, 29, 22, 20],
       [10,  3, 16,  4],
       [11,  7, 27, 12],
       [12, 20,  9, 21],
       [13, 28,  7, 27],
       [14,  1,  3, 11],
       [15, 26,  1,  0],
       [16, 13, 28,  2],
       [17, 19,  8,  3],
       [18, 12, 20, 16],
       [19, 27, 23, 10],
       [20, 24, 14, 15],
       [21, 16, 27,  8],
       [22, 28,  3, 15],
       [23,  8, 29, 19],
       [24, 21,  2,  1],
       [25, 14,  2, 11],
       [26, 10,  4, 12],
       [27, 25, 13,  0],
       [28,  8, 27,  2],
       [29,  0, 11, 28]])