In [1]:
from src.solution import *
import src.operators as op
import testFunctions as tf
import numpy as np

In [2]:
Solution.setProblem(tf.ackley_function, (-1,+1), 5, maximize=False)
X = Solution.initialize(4)
for Xi in X:    Xi.setX(op.init_random(*Solution.bounds, Solution.dimension))
[Xi.getFitness() for Xi in X], "nfe: "+str(Solution.nfe), Solution.best.fitness
[Xi.updatePBest() for Xi in X]

op.param = {"w":1,"c1":1,"c2":1,"alpha":.7,"beta":.5,"pr":.6}

In [ ]:
## be sure it really does what you think

U = X
round:
    #input selection
    S1 = op.select_random(U, 1)
    S2 = op.select_random(U, 1)
    S  = np.append(S1, S2, axis=1)
    #operator
    V = op.w_crx_blend(S)
    #update rule
    U = op.pool(U, V)
#     U = op.replace_if_best(U, V)
X = U

In [8]:
u = np.array([xi for xi in X[0].x])
u

array([ 0.3523674 ,  0.96937127,  0.17209415, -0.16955068, -0.21302916])

In [15]:
ind_ub = u>.4
ind_lb = u<0

ind_ub, ind_lb

(array([False,  True, False, False, False]),
 array([False, False, False,  True,  True]))

In [34]:
indices = (u>11) + (u<5)
u[indices]

array([0, 0, 0, 0])

In [33]:
u = np.array([0, 0, 10, 10, 0, 0])

In [14]:
ind_ub + ind_lb

array([ True,  True,  True,  True,  True])

In [47]:
u[indices] = np.random.uniform(-10, -1, len(u[indices]))
u

array([-2, -4, 10, 10, -5, -3])

In [32]:
u

array([0.3523674 , 0.2120326 , 0.17209415, 0.39710522, 0.29063104])

In [53]:
def select_random(X, n):
    """ Selects n exclusively and randomly candidate solutions from X
    :param X: list of candidate solutions
    :param n: the number of individuals selected
    :returns: A list of references of the selected candidate solutions. """
    s = [np.random.choice(X, n, replace=False) for _ in range(len(X))]
    return np.array(s)

def select_tournament(X, n, k): 
    """ Selects n exclusively candidate solutions from X through tournament of group size k
    :param X: list of candidate solutions
    :param n: the number of individuals selected
    :param k: group size
    :returns: A list of references of the selected candidate solutions. """
    s = [np.sort(r)[::-1][:n] for r in select_random(X, k)]
    return np.array(s)

select_tournament(X, 2, 2)

array([[<src.solution.Solution object at 0x000001A4ED808EB8>,
      dtype=object)

In [52]:
select_random(X, 1)

array([[<src.solution.Solution object at 0x000001A4ED808E48>],
      dtype=object)

In [ ]:
s1 = op.select_current(X)
# s2 = op.select_current(X)
s3 = op.select_random(X, 1)
# S = np.append(s1, s3, axis=1)
S = s1
s1